//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageBoard.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MessageBoardEntities : DbContext
    {
        public MessageBoardEntities()
            : base("name=MessageBoardEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MajorMessageList> MajorMessageList { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<MessagePic> MessagePic { get; set; }
        public virtual DbSet<OperateLog> OperateLog { get; set; }
        public virtual DbSet<UserList> UserList { get; set; }
        public virtual DbSet<UserLog> UserLog { get; set; }
    }
}
